on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_FILE }}
          port: ${{ secrets.EC2_PORT }}
          source: .
          target: /home/ubuntu/my-app

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_FILE }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/my-app
            docker build -t my-app .
            docker stop my-app-container || true
            docker rm my-app-container || true
            docker run -d -p 8000:8000 --name my-app-container my-app
